[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
  for = "/index.html"
  [headers.values]
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''

  for = "/fonts/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable'''